### ISSUE TITLE
Examples from Jupyter notebook

### ISSUE THREAD

**Issue by schoeberl** [schoeberl/chisel-lab#1]
I think we should add your exercises as plain Chisel/Scala files with a README.md for the text and not dumping all Jupyter notebook stuff into this repo. There is still the Jupyter repo, we will not delete that one.

Martin

**Comment by nothinn** [comment]
We are en route for this.  The four examples have been converted, but some still need a look through.

**Comment by schoeberl** [comment]
Appears to be done.
