### ISSUE TITLE
coursier error

### ISSUE THREAD

**Issue by fatalfeel** [schoeberl/chisel-lab#4]
curl -Lo coursier https://git.io/coursier
chmod +x coursier

coursier will error
///////////////////////////////////////////////////////////// modify to this
#install coursier: https://get-coursier.io/docs/1.1.0-M10/cli-overview
curl -L -o coursier https://git.io/coursier-cli && chmod +x coursier && ./coursier --help

pip3 install jupyter
export SCALA_VERSION=2.12.8
export ALMOND_VERSION=0.2.1
./coursier bootstrap -r jitpack -i user -I user:sh.almond:scala-kernel-api_$SCALA_VERSION:$ALMOND_VERSION sh.almond:scala-kernel_$SCALA_VERSION:$ALMOND_VERSION -o almond
./almond --install

**Comment by schoeberl** [comment]
I am not sure what you are meaning here. We are not using the jupyter notebook. Maybe I should delete it.
