### ISSUE TITLE
sbt install method

### ISSUE THREAD

**Issue by fatalfeel** [schoeberl/chisel-lab#5]
This is correct install way
#install scala tool: https://www.scala-sbt.org/download.html
echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
sudo apt update
sudo apt install sbt

**Comment by fatalfeel** [comment]
all the fixed and install and simulation here
http://fatalfeel.blogspot.com/2013/12/chisel-design-ic-for-risc-v.html

**Comment by schoeberl** [comment]
I guess this is obsolete now.
